version: '2'
services:
  mysql:
    image: mysql/mysql-server:8.0
    command: mysqld --disable-log-bin --collation-server=utf8mb4_bin --max-connections=2000
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    cap_add:
      - SYS_NICE
    volumes:
      - /home/makoto/extdisk/home/makoto/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    # pids_limit: 4000
    ulimits:
      nproc: 10000
      nofile:
        soft: 10000
        hard: 10000
